### ISSUE TITLE
Non Exported Interfaces in Generated Typescript File

### ISSUE THREAD

**Issue by anthonymichaelson** [code-star/scala-tsi#28]
As a newcomer to Typescript it's confusing to see the file generated by scala-tsi to not have any exported interfaces. It's unclear how to import the interfaces from the file that is produced. Either an option should be created for the scala-tsi sbt plugin to prefix the generated interfaces with "export " or the expected method for utilizing the generated typescript file should be added to README.md.

Can @dhoepelman or @mdvanes provide some clarity on this please?

**Comment by anthonymichaelson** [comment]
Ok, though I stumbled upon the answer, according to typescriptlang.org utilizing `import './filePath'` is _"not recommended practice"_. https://www.typescriptlang.org/docs/handbook/modules.html

At least I'm able to get going but it's rather awkward to be without the ability to only import specific interfaces or to do `import * as objectName from './filePath'`.

What are your thoughts on this?

**Comment by dhoepelman** [comment]
Thanks for the interest Anthony. The project is still in a 0.1 state, so you're right that this is not ideal.
One thing it [should have](https://github.com/code-star/scala-tsi/issues/1) is full support for modules.

Adding `export` is to interfaces a quick win, I'll make a version that does that

**Comment by anthonymichaelson** [comment]
Hi @dhoepelman - I can do it also. Would you like me to send a PR? It'll take me about a week to get it to you.

**Comment by dhoepelman** [comment]
No need, if my co-author agrees I'll merge #13 and release 0.1.3 with it

**Comment by anthonymichaelson** [comment]
Great to hear, thank you so much!

**Comment by dhoepelman** [comment]
[0.1.3](https://github.com/code-star/scala-tsi/releases/tag/0.1.3) was just released, with this change included. @anthonymichaelson Let me know if it solves your issue or if you need any more help
