### ISSUE TITLE
Add Semicolon to interfaces and other declarations

### ISSUE THREAD

**Issue by b-eyselein** [code-star/scala-tsi#54]
In the [Typescript Guide](https://www.typescriptlang.org/docs/handbook/interfaces.html) members of interfaces and other declarations are closed with a semicolon.

Also the default configuration of TSLint that comes with Angular wants members of interfaces closed with a semicolon.

Could you add the possibility to generate interfaces with semicolons?

**Comment by dhoepelman** [comment]
[I see it's the recommendation in the style guide](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#semicolons), so it should be possible and the default

**Comment by dhoepelman** [comment]
Hey @b-eyselein 

I've added some support in the upcoming 0.2.0, but left it off by default because it's tricky to find all the cases where it's required. Give it a spin!
