### ISSUE TITLE
Cannot Generate TS files on Windows

### ISSUE THREAD

**Issue by jordanburke** [code-star/scala-tsi#55]
Hi, the creation of the TS file fails on Windows due to file path not having properly escaped \ in generated string:

`.generateTypescriptApplicationTemplate(imports, typesToGenerate, typescriptOutputFile.getAbsolutePath)` 

in TypescriptGenPlugin.scala

typescriptOutputFile.getAbsolutePath output string needs every '\' converted to a '\\' so that it can be picked up properly in the generated code.

Great plugin btw, been using it for months (i.e., on OSX) and it's been extremely useful.

**Comment by dhoepelman** [comment]
Hi @jordanburke 

glad to hear you're enjoying the plugin. Are you using 0.1.4 or 0.2.0-SNAPSHOT?

**Comment by jordanburke** [comment]
@dhoepelman 

Thanks for getting back so quickly. I was on 0.1.3 (wasn't aware of 0.1.4), though the problem is also in master. I've forked it locally and patched it here https://github.com/sapienapps/scala-tsi/commit/94d91785a72ffc7d764127ea549060775ac3b529 to allow work on my window's machine. You can ignore the version change file as I'm still on 2.12 currently.

**Comment by dhoepelman** [comment]
Fixed in #60, will include in 0.2.0 which I aim to release later today

**Comment by jordanburke** [comment]
Just to circle back @dhoepelman, I picked up latest a few days ago and it's working great on Windows now (along with the other changes). Thanks again!
